services:
  sb-ecommerce-api-app:
    image: gradle:8.4.0-jdk21
    container_name: sb-ecommerce-api-app
    working_dir: /app
    command: gradle bootRun --no-daemon
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    env_file:
      - .env
    depends_on:
      - sb-ecommerce-api-mongodb

  sb-ecommerce-api-mongodb:
    image: mongo:latest
    container_name: sb-ecommerce-api-mongodb
    ports:
      - "27017:27017"
    volumes:
      - sb-ecommerce-api-mongo-data:/data/db

volumes:
  sb-ecommerce-api-mongo-data:
