services:
  sb-ecommerce-api-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sb-ecommerce-api-app-dev
    working_dir: /app
    command: gradle bootRun --no-daemon
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
      - ~/.gradle:/home/gradle/.gradle
    env_file:
      - .env
    depends_on:
      - sb-ecommerce-api-dev-mongodb
    networks:
      - app-tier
  sb-ecommerce-api-dev-mongodb:
    image: mongo:latest
    container_name: sb-ecommerce-api-dev-mongodb
    ports:
      - "27017:27017"
    volumes:
      - sb-ecommerce-api-mongo-data:/data/db
    networks:
      - app-tier

volumes:
  sb-ecommerce-api-mongo-data:

networks:
  app-tier:
