services:
  sb-ecommerce-api-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sb-ecommerce-api-app
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
      - ~/.gradle:/home/gradle/.gradle
    env_file:
      - .env
    depends_on:
      - sb-ecommerce-api-mongodb

  sb-ecommerce-api-mongodb:
    image: mongo:latest
    container_name: sb-ecommerce-api-mongodb
    ports:
      - "27017:27017"
    volumes:
      - sb-ecommerce-api-mongo-data:/data/db

volumes:
  sb-ecommerce-api-mongo-data:
