services:
  sb-ecommerce-api-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb-ecommerce-api-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sb-ecommerce-api-mongodb
    networks:
      - app-tier
  sb-ecommerce-api-mongodb:
    image: mongo:latest
    container_name: sb-ecommerce-api-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - sb-ecommerce-api-mongo-data:/data/db
    networks:
      - app-tier

volumes:
  sb-ecommerce-api-mongo-data:

networks:
  app-tier:
    driver: bridge