services:
  sb-ecommerce-api-app:
    image: melvstein/sb-ecommerce-api:latest
    build:
      context: .
      dockerfile: ${BUILD_DOCKER_FILE:-development/Dockerfile}
    container_name: sb-ecommerce-api-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sb-ecommerce-api-mongodb
  sb-ecommerce-api-mongodb:
    image: mongo:latest
    container_name: sb-ecommerce-api-mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - sb-ecommerce-api-mongo-data:/data/db

volumes:
  sb-ecommerce-api-mongo-data:
